Id:             'MSYS2-SLiM'                ## Application package name ie. chrome-cornell
Description:    'MSYS2 with post-install SLiM'    ## Application packages description
Version:        '20251213'                     ## Application version number - MUST BE in #.# format

Install:                                    ## If there are installation files in a .zip to be installed, specify here
  - File:       '%INSTALL_DIR%\msys2.exe'   ## Installation file
    FileType:   'exe'                       ## exe or msi are the only options currently
    Arguments:  'in --confirm-command --accept-messages --root C:/msys64'        ## Silent installation switches/parmeters
    ExitCodes:  [0]                         ## Exit codes - returns a success

Applications:                                                       ## Applications to be published to the user / Added to Image Assistant
    SLiMgui:                                                      ## This must match the icons.png file name
        DisplayName:    'SliMgui'                ## How the app displayed to the user
        Path:           'C:\msys64\mingw64\bin\SliMgui.exe'          ## The path to the app
        LaunchParams:   ''                     ## Launch parameters for the app
        WorkDir:        '' ## Working directory

    slim:                                                      ## This must match the icons.png file name
        DisplayName:    'SliMgui'                ## How the app displayed to the user
        Path:           'C:\msys64\mingw64\bin\slim.exe'          ## The path to the app
        LaunchParams:   ''                     ## Launch parameters for the app
        WorkDir:        '' ## Working directory
    
    eidos:                                                      ## This must match the icons.png file name
        DisplayName:    'SliMgui'                ## How the app displayed to the user
        Path:           'C:\msys64\mingw64\bin\eidos.exe'          ## The path to the app
        LaunchParams:   ''                     ## Launch parameters for the app
        WorkDir:        '' ## Working directory