Id:             'MSYS2-SLiM'                ## Application package name ie. chrome-cornell
Description:    'MSYS2 with post-install SLiM'    ## Application packages description
Version:        '2025.12.13'                     ## Application version number - MUST BE in #.# format

ChocoPackages:                              ## Chocolatey packages installed straight from Chocolatey Gallery
  - PackageName:    'msys2'     ## Package name - https://chocolatey.org/packages - ie. adobereader
    InstallParams:  '/NoUpdate /InstallDir:C:\msys64' 

Install:                                    ## If there are installation files in a .zip to be installed, specify here
  # - File:       '%INSTALL_DIR%\msys2.exe'   ## Installation file
  #   FileType:   'exe'                       ## exe or msi are the only options currently
  #   Arguments:  'in --confirm-command --accept-messages --root %PROGRAMFILES(x86)%\msys64 --accept-licenses --default-answers --verbose'        ## Silent installation switches/parmeters
  #   ExitCodes:  [0]                         ## Exit codes - returns a success
    
  - File:       '%windir%\System32\WindowsPowerShell\v1.0\powershell.exe'
    FileType:   'exe'
    Arguments:  '-ExecutionPolicy ByPass -NoExit -Command "& $env:SYSTEMDRIVE\msys64\msys2_shell.cmd -defterm -no-start -mingw64 -c `"pacman -Syu --noconfirm`""'
    ExitCodes:   [0]

  - File:       '%windir%\System32\WindowsPowerShell\v1.0\powershell.exe'
    FileType:   'exe'
    Arguments:  '-ExecutionPolicy ByPass -NoExit -Command "& $env:SYSTEMDRIVE\msys64\msys2_shell.cmd -defterm -no-start -mingw64 -c `"pacman -S --noconfirm mingw-w64-x86_64-slim-simulator`""'
    ExitCodes:   [0]

Applications:                                                       ## Applications to be published to the user / Added to Image Assistant
    SLiMgui:                                                      ## This must match the icons.png file name
        DisplayName:    'SliMgui'                ## How the app displayed to the user
        Path:           'C:\msys64\mingw64\bin\SliMgui.exe'          ## The path to the app
        LaunchParams:   ''                     ## Launch parameters for the app
        WorkDir:        '' ## Working directory

    slim:                                                      ## This must match the icons.png file name
        DisplayName:    'slim'                ## How the app displayed to the user
        Path:           'C:\msys64\mingw64\bin\slim.exe'          ## The path to the app
        LaunchParams:   ''                     ## Launch parameters for the app
        WorkDir:        '' ## Working directory
    
    eidos:                                                      ## This must match the icons.png file name
        DisplayName:    'eidos'                ## How the app displayed to the user
        Path:           'C:\msys64\mingw64\bin\eidos.exe'          ## The path to the app
        LaunchParams:   ''                     ## Launch parameters for the app
        WorkDir:        '' ## Working directory - small modification to confirm new codebuild
