Id:             'MSYS2-SLiM'                ## Application package name ie. chrome-cornell
Description:    'MSYS2 with post-install SLiM'    ## Application packages description
Version:        '2025.12.13'                     ## Application version number - MUST BE in #.# format

ChocoPackages:                              ## Chocolatey packages installed straight from Chocolatey Gallery
  - PackageName:    'msys2'     ## Package name - https://chocolatey.org/packages - ie. adobereader
    InstallParams:  '/NoUpdate' 

Install:                                    ## If there are installation files in a .zip to be installed, specify here   
  - File:       '%windir%\System32\WindowsPowerShell\v1.0\powershell.exe'
    FileType:   'exe'
    Arguments:  "-ExecutionPolicy ByPass -Command \"& $env:SystemDrive\\tools\\msys64\\msys2_shell.cmd -defterm -no-start -mingw64 -c 'pacman -Syu --noconfirm'\""
    ExitCodes:  [0]

  - File:       '%windir%\System32\WindowsPowerShell\v1.0\powershell.exe'
    FileType:   'exe'
    Arguments:  "-ExecutionPolicy Bypass -Command \"& $env:SystemDrive\\tools\\msys64\\msys2_shell.cmd -defterm -no-start -mingw64 -c 'pacman -S --noconfirm mingw-w64-x86_64-slim-simulator'\""
    ExitCodes:  [0]

Files: 
    '%SYSTEMDRIVE%\tools\msys64\msys2_shell.cmd': '%SYSTEMDRIVE%\tools\msys64\msys2_shell.bat'

Applications:                                                       ## Applications to be published to the user / Added to Image Assistant
    SLiMgui:                                                      ## This must match the icons.png file name
        DisplayName:    'SliMgui'                ## How the app displayed to the user
        Path:           '%WINDIR%\System32\WindowsPowerShell\v1.0\powershell.exe'          ## The path to the app
        LaunchParams:   '-ExecutionPolicy ByPass -Command "& C:\tools\msys64\mingw64\bin\SliMgui.exe"'                     ## Launch parameters for the app
        WorkDir:        '' ## Working directory

    mingw64:                                                      ## This must match the icons.png file name
        DisplayName:    'mingw64'                ## How the app displayed to the user
        Path:           '%SYSTEMDRIVE%\tools\msys64\msys2_shell.bat'          ## The path to the app
        LaunchParams:   '-mingw64 -where %SYSTEMDRIVE%\tools\msys64\mingw64\bin'                     ## Launch parameters for the app
        WorkDir:        '' ## Working directory

    msys2:                                                      ## This must match the icons.png file name
        DisplayName:    'msys2'                ## How the app displayed to the user
        Path:           '%SYSTEMDRIVE%\tools\msys64\msys2_shell.bat'          ## The path to the app
        LaunchParams:   '-msys2 -where %SYSTEMDRIVE%\tools\msys64\mingw64\bin'                     ## Launch parameters for the app
        WorkDir:        '' ## Working directory
    
    # eidos:                                                      ## This must match the icons.png file name
    #     DisplayName:    'eidos'                ## How the app displayed to the user
    #     Path:           '%WINDIR%\System32\WindowsPowerShell\v1.0\powershell.exe'         ## The path to the app
    #     LaunchParams:   '-ExecutionPolicy ByPass -WindowStyle Hidden -NoExit -Command "& $env:SYSTEMDRIVE\tools\msys64\mingw64\bin\eidos.exe"'   ## Launch parameters for the app
    #     WorkDir:        '' ## Working directory - small modification to confirm new codebuild
