Id:             'k2cit-cornell'
Description:    'k2cit-cornell'
Version:        '7.8.0.5'

Install:
  - File:       '%INSTALL_DIR%\ksp-client-x64.exe'
    FileType:   'exe'
    Arguments:  '-new -q -v PROP_HOSTNAME=%HOSTNAME% -v PROP_SITE=%AppStream_Resource_Name% -v PROP_USERNAME=%AoD_Combo% -v PROP_LAUNCH=0 -v PROP_REBOOT=0'
    ExitCodes:  [0]
