Id:             'ansys-base'
Description:    'ANSYS 2025 R2 SP4 - COECIS License'
Version:        '25.2.04.0'

Install:
  - File:       '%INSTALL_DIR%\setup.exe'
    FileType:   'exe' 
    Arguments:  '-optislang -fluent -mechapdl -licserverinfo %LIC_SERVER% -silent'
    ExitCodes:  [0]

  - File:       '%INSTALL_DIR%\SPACECLAIM_2025R2\setup.exe'
    FileType:   'exe' 
    Arguments:  '-silent'
    ExitCodes:  [0]
    
Applications:
    ANSYSWB:
        DisplayName:    'Workbench 2025 R2.04'
        Path:           '%PROGRAMFILES%\ANSYS Inc\v252\Framework\bin\Win64\RunWB2.exe'
        LaunchParams:   ''
        WorkDir:        ''

    SPACECLAIM:
        DisplayName:    'SpaceClaim 2025 R2'
        Path:           '%PROGRAMFILES%\ANSYS Inc\v252\scdm\SpaceClaim.exe'
        LaunchParams:   ''
        WorkDir:        ''

Files: 
    '%INSTALL_DIR%\ApipUserConfig.txt': '%SYSTEMDRIVE%\Users\Default\AppData\Roaming\Ansys\v252\ApipUserConfig.txt'
    # '%INSTALL_DIR%\CADConfigurationInfo.XML': '%PROGRAMFILES%\ANSYS Inc\v252\commonfiles\CAD\CADConfigurationInfo.XML'
    # '%INSTALL_DIR%\ansyslmd.ini': '%PROGRAMFILES%\ANSYS Inc\Shared Files\Licensing\ansyslmd.ini'

Registry:               
    HKUD:               
        SOFTWARE\SpaceClaim\SIP:
            Displayed:
                Type:   'String'
                Value:  '1'