Id:             'Academic-Healthcare-SimLab' ## this comment added for second attemot to get buold and test off of branch
Description:    'Academic Healthcare SimLab'
Version:        '1.1'

Applications:
    Academic-Healthcare-SimLab:
        DisplayName:    'Academic Healthcare SimLab'
        Path:           '%PROGRAMFILES%\Academic Healthcare SimLab\Academic Healthcare SimLab.exe'
        LaunchParams:   ''
        WorkDir:        ''

Files:
    '%INSTALL_DIR%\Academic Healthcare SimLab.exe': '%PROGRAMFILES%\Academic Healthcare SimLab\Academic Healthcare SimLab.exe'
