Id:             'Academic-Healthcare-SimLab' ## third time is a charm testing
Description:    'Academic Healthcare SimLab - test build'
Version:        '1.1'

Applications:
    Academic-Healthcare-SimLab:
        DisplayName:    'Academic Healthcare SimLab'
        Path:           '%PROGRAMFILES%\Academic Healthcare SimLab\Academic Healthcare SimLab.exe'
        LaunchParams:   ''
        WorkDir:        ''

Files:
    '%INSTALL_DIR%\Academic Healthcare SimLab.exe': '%PROGRAMFILES%\Academic Healthcare SimLab\Academic Healthcare SimLab.exe'
